services:
  - type: web
    name: papers-scraper
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --worker-class gevent --workers 2 --timeout 120
    plan: free
